config/routes.rb
BookStore::Application.routes.draw do
  
  namespace :admin do
    resources :books do
      collection do
        post 'reorder'
      end
      member do
        get 'row'
      end
    end
    resources :categories do
      resources :books
    end
    root to: 'books#index'
  end

  devise_for :managers
  devise_for :customers

  resources :categories do
    resources :books
  end
  resources :books

  resources :carts do
    collection do
      post 'order'
      get  'thanks'
      get  'create_and'
    end
  end

  root to: 'categories#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category

  validates_presence_of :isbn, :title, :price, :category_id
  validates_numericality_of :price, allow_blank: true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :book
  belongs_to :customer

  validates_presence_of :customer_id, :book_id, :quantity
  validates_numericality_of :quantity, allow_blank: true

  def self.list(customer_id)
    Cart.where(:customer_id => customer_id).order(:created_at)
  end

  def self.total(customer_id)
    self.list(customer_id).inject(0) {|total, cart|  total + cart.book.price * cart.quantity}
  end

  def self.checkout(customer_id)
    Cart.where(:customer_id => customer_id).delete_all
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/.#carts_controller.rb
uchikawa_takao@YG35-37221.local.3167

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  layout 'admin'

  before_action :authenticate_manager!
  before_action :set_admin_book, only: [:show, :edit, :update, :destroy]

  # GET /admin/books
  def index
    if params[:category_id]
      @books = Book.where(category_id: params[:category_id]).order(:display_order)
    else
      @books = Category.first.books.order(:display_order)
    end
    render layout: 'admin'
  end

  # GET /admin/books/1
  def show
  end

  # GET /admin/books/new
  def new
    @book = Book.new
  end

  # GET /admin/books/1/edit
  def edit
  end

  # POST /admin/books
  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to admin_book_path(@book), notice: '作成しました'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/books/1
  def update
    if @book.update(book_params)
      redirect_to admin_book_path(@book), notice: '更新しました'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/books/1
  def destroy
    @book.destroy
    redirect_to admin_books_url, notice: '削除しました'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:isbn, :title, :author, :price, :category_id, :icon_path, :picture_path, :description, :display_order)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    if resource.is_a?(Manager)
      admin_books_path
    else
      if session[:cart_entry]
        create_and_carts_path
      else
        categories_path
      end
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:category_id]
      @books = Book.where(category_id: params[:category_id]).order(:display_order)
    else
      @books = Book.order(:display_order).all
    end
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  def index
    @carts = Cart.list(current_customer.id)
    @total = Cart.total(current_customer.id)
  end

  def edit
  end

  def create
    @cart = Cart.new(cart_params)
    @cart.customer_id = current_customer.id

    if @cart.save
      redirect_to carts_url
    else
      render action: "new"
    end
  end

  def update
    if @cart.update_attributes(cart_params)
      redirect_to carts_url
     else
      render action: "edit"
    end
  end

  def destroy
     @cart.destroy
    redirect_to carts_url
  end

  def order
    Cart.checkout(current_customer.id)
    redirect_to thanks_carts_path
  end

  def create_and
    if session[:cart_entry]
      cart_params = session[:cart_entry]
      cart_params.permit!
      cart_params[:customer_id] = current_customer.id

      cart = Cart.new(cart_params)
      cart.save
      session[:cart_entry] = nil
    end
    redirect_to carts_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:book_id, :customer_id, :quantity)
    end

    def authenticate
      session[:cart_entry] = params[:cart]  if !customer_signed_in? && params[:cart]
      authenticate_customer!
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.order(:display_order)
  end
end

app/controllers/customers_controller.rb
class CustomersController < Devise::SessionsController
end

app/controllers/managers_controller.rb
class ManagersController < Devise::SessionsController
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def yen(n)
    "￥#{number_with_delimiter(n)}"
  end

  def display_base_errors(resource)
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/views/admin/books/_form.html.erb
<%= form_for @book, url: @book.id ? admin_book_path(@book) : admin_books_path,
  html: { class: 'form-horizontal' } do |f| %>

    <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @book.errors.count %>つの入力間違いがあります:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :isbn, class: 'control-label' %>
    <div class="controls"><%= f.text_field :isbn %></div>
  </div>
  <div class="control-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls"><%= f.text_field :title, class: 'input-xlarge' %></div>
  </div>
  <div class="control-group">
    <%= f.label :author, class: 'control-label' %>
    <div class="controls"><%= f.text_field :author %></div>
  </div>
  <div class="control-group">
    <%= f.label :price, class: 'control-label' %>
    <div class="controls"><%= f.number_field :price %></div>
  </div>
  <div class="control-group">
    <%= f.label :category_id, class: 'control-label' %>
    <div class="controls"><%= f.select :category_id, Category.order(:id).map{|c| [c.name, c.id]} %></div>
  </div>
  <div class="control-group">
    <%= f.label :display_order, class: 'control-label' %>
    <div class="controls"><%= f.number_field :display_order %></div>
  </div>
  <div class="control-group">
    <%= f.label :description, class: 'control-label' %>
    <div class="controls"><%= f.text_area :description, rows: 10, class: 'input-xxlarge' %></div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= link_to "戻る", admin_books_path, class: 'btn' %>
  </div>
<% end %>

app/views/admin/books/_row.html.erb
      
        <td><%= image_tag @book.icon_path %></td>
        <td><%= @book.title %></td>
        <td><%= @book.author %></td>
        <td><%= yen @book.price %></td>
        <td>
          <%= link_to '詳細', admin_book_path(@book), remote: true, class: 'show_button btn btn-small' %>
          <%= link_to '編集', edit_admin_book_path(@book), remote: true, class: 'edit_button btn btn-small btn-primary' %>
          <%= link_to '削除', admin_book_path(@book), method: :delete, data: { confirm: "「#{@book.title}」を削除しますか?" }, class: 'btn btn-small btn-danger' %>
        </td>

app/views/admin/books/edit.html.erb
<h1>編集</h1>

<%= render 'form' %>

app/views/admin/books/index.html.erb
<div class="page-header">
  <h1>書籍管理</h1>
</div>

<%= select_tag "category_selector", options_for_select(Category.all.map{|c| [c.name, c.id]}, @books.first.category_id) %>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>タイトル</th>
      <th>著者</th>
      <th>値段</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr id="<%= "row_#{book.id}" %>">
        <td><%= image_tag book.icon_path %></td>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= yen book.price %></td>
        <td>
          <%= link_to '詳細', admin_book_path(book), class: 'btn btn-small' %>
          <%= link_to '編集', edit_admin_book_path(book), class: 'btn btn-small btn-primary' %>
          <%= link_to '削除', admin_book_path(book), method: :delete, data: { confirm: "「#{book.title}」を削除しますか?" }, class: 'btn btn-small btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<%= link_to '新規作成', new_admin_book_path, class: 'btn' %>

<%= javascript_tag do -%>
$("#category_selector").change(function() {
  location.href = "<%= admin_category_books_path(9999) %>".replace('9999', $(this).val());
});
<% end %>

app/views/admin/books/new.html.erb
<h1>新規作成</h1>

<%= render 'form' %>

app/views/admin/books/show.html.erb
<div class="page-header">
  <h1><%= @book.title %></h1>
</div>

<div class="row">
  <div class="span4">
    <%= image_tag @book.picture_path %>
  </div>
  <div class="span5">
    <dl class="dl-horizontal">
      <dt><strong>タイトル</strong></dt>
      <dd><%= @book.title %></dd>
      <dt><strong>著者</strong></dt>
      <dd><%= @book.author %></dd>
      <dt><strong>価格</strong></dt>
      <dd><%= yen @book.price %></dd>
      <dt><strong>カテゴリー</strong></dt>
      <dd><%= @book.category.name %></dd>
      <dt><strong>ISBN</strong></dt>
      <dd><%= @book.isbn %></dd>
      <dt><strong>表示順</strong></dt>
      <dd><%= @book.display_order %></dd>
      <dt><strong>内容</strong></dt>
      <dd><%= @book.description %></dd>
    </dl>
    <div class="form-actions">
      <%= link_to '編集', edit_admin_book_path(@book), class: 'btn btn-primary' %>
      <%= link_to '戻る', admin_books_path, class: 'btn' %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="page-header">
  <h1>書籍 : <%= @books.first.category.name %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>タイトル</th>
      <th>著者</th>
      <th>値段</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to (image_tag book.icon_path), book %></td>
        <td><%= link_to book.title, book %></td>
        <td><%= book.author %></td>
        <td><%= yen book.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<div class="page-header">
  <h1><%= @book.title %></h1>
</div>

<div class="row">
  <div class="span4">
    <%= image_tag @book.picture_path %>
  </div>
  <div class="span5">
    <dl class="dl-horizontal">
      <dt><strong>タイトル</strong></dt>
      <dd><%= @book.title %></dd>
      <dt><strong>著者</strong></dt>
      <dd><%= @book.author %></dd>
      <dt><strong>価格</strong></dt>
      <dd><%= yen @book.price %></dd>
      <dt><strong>カテゴリー</strong></dt>
      <dd><%= @book.category.name %></dd>
      <dt><strong>ISBN</strong></dt>
      <dd><%= @book.isbn %></dd>
      <dt><strong>内容</strong></dt>
      <dd><%= @book.description %></dd>
    </dl>

    <div class="form-actions">
      <%= link_to "戻る", category_books_path(@book.category_id), class: 'btn'  %>
      <%= link_to "カートに入れる", carts_path("cart[book_id]" => @book.id, "cart[quantity]" => 1),
            method: :post, class: 'btn' %>
    </div>
  </div>
</div>

app/views/carts/_form.html.erb
<%= form_for @cart, html: { class: 'form-horizontal' } do |f| %>

  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= @cart.errors.count %>つの入力間違いがあります:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :book_id, class: 'control-label' %>
    <div class="controls">
      <%= @cart.book.title %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :quantity, class: 'control-label' %>
    <div class="controls">
      <%= f.number_field :quantity, class: 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= link_to "戻る", carts_path, class: 'btn' %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<div class="page-header">
  <h1>数量変更</h1>
</div>
<%= render 'form' %>

app/views/carts/index.html.erb
<div class="page-header">
  <h1>ショッピングカート</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="2">書籍</th>
      <th>価格</th>
      <th>数量</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= image_tag cart.book.icon_path %></td>
        <td><%= cart.book.title %></td>
        <td><%= yen cart.book.price %></td>
        <td><%= cart.quantity %></td>
        <td>
          <%= link_to "数量変更", edit_cart_path(cart), class: 'btn btn-mini' %>
          <%= link_to "削除", cart, method: :delete, data: { confirm: '削除して良いですか？' }, class: 'btn btn-mini' %>
         </td>
      </tr>
    <% end %>
      <tr>
        <th colspan="4">合計</th>
        <td colspan="1"><%= yen @total%></td>
      </tr>  
  </tbody>
</table>

<div class="row">
  <div class="span4 offset8">
    <%= link_to '購入', order_carts_path, method: :post, class: 'btn btn-large btn-primary' %>
    <%= link_to '戻る', root_path, class: 'btn btn-large' %>
  </div>
</div>

app/views/carts/thanks.html.erb
<div class="row">
  <div class="span6 offset3">
    <div style="height:80px">&nbsp;</div>
    <h1>お買い上げありがとうございます。</h1>
  </div>
</div>

app/views/categories/index.html.erb
<div class="page-header">
  <h1>カテゴリー</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>カテゴリー</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category_books_path(category.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/admin.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BookStore Admin" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= link_to "BookStore Admin", admin_books_path, class: 'brand' %>
          <ul class="pull-right nav">
            <li><a><strong><%= manager_signed_in? ? current_manager.name : "" %></a></strong></li>
            <% if manager_signed_in? %>
            <li><%= link_to "ログアウト", destroy_manager_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to "ログイン", new_manager_session_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <% flash.each do |name, msg| %>
                <% if msg.is_a?(String) %>
                  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                    <a class="close" data-dismiss="alert">&#215;</a>
                    <%= content_tag :div, msg, id: "flash_#{name}" %>
                  </div>
                <% end %>
              <% end %>

              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BookStore" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= link_to "BookStore", root_path, class: 'brand' %>
          <ul class="pull-right nav">
            <li><a><strong><%= customer_signed_in? ? current_customer.name + " 様" : "" %></a></strong></li>
            <% if customer_signed_in? %>
            <li><%= link_to "カート表示", carts_path  %></li>
            <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to "ログイン", new_customer_session_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <% flash.each do |name, msg| %>
                <% if msg.is_a?(String) %>
                  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                    <a class="close" data-dismiss="alert">&#215;</a>
                    <%= content_tag :div, msg, id: "flash_#{name}" %>
                  </div>
                <% end %>
              <% end %>

              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>